variables:
  DOCKER_DRIVER: overlay2

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

stages:
  - test
  - deploy

test:
  image: python:3.8-buster
  services:
    - docker:dind
  stage: test
  script:
    - pip install tox
    - tox
  artifacts:
    reports:
      junit: junit-*.xml

# A more complicated CI/CD pipeline would build, then test, then deploy. For simplicity,
# this configuration runs the stages separately with no shared artefacts.
deploy:
  image: python:3.8-buster
  services:
    - docker:dind
  stage: deploy
  script:
    - rm -rf dist
    - pip install twine wheel
    - python3 setup.py sdist bdist_wheel
    - sed -i "s|%TOKEN%|${PYPI_TOKEN}|" .pypirc
    - python3 -m twine upload --config-file .pypirc --repository pypi dist/*

  # Ensure we only push when a new version is tagged
  only:
    - tags
    - /^v\d+\.\d+\.\d+$$/